### ISSUE TITLE
Udacity Dataset Queries

### ISSUE THREAD

**Issue by omerqureshi84** [Intenzo21/Brain-Inspired-Deep-Imitation-Learning-for-Autonomous-Driving-Systems#2]
In the research, the lakeside track is used for training (8K instances) and jungle track (21K instances) for testing.

Why is it that the lakeside is used for training when it has lower instances?

In the lakeside track, if we plot the steering angles, there are overwhelming number of 0 values. It has not been mentioned in research as to what steps were taken to counter this

Highly appreciate if you could shed some light on the above points.

**Comment by Intenzo21** [comment]
> In the research, the lakeside track is used for training (8K instances) and jungle track (21K instances) for testing.
> 
> Why is it that the lakeside is used for training when it has lower instances?

The jungle track is relatively ’darker’ since there are trees, hills and mountains which throw shadows over the lanes, and also tight turns and other features not included in the lakeside track. Therefore, the jungle dataset is the more challenging among the two. It is used as a testing ground for the already trained models on the sunny lakeside map. The developed architectures were evaluated with no prior knowledge about the features of the map. The reason behind is to assess the generalisability of the outputs in a previously completely unseen environment.

> In the lakeside track, if we plot the steering angles, there are overwhelming number of 0 values. It has not been mentioned in research as to what steps were taken to counter this

We include steering angle data augmentation and balancing to support us in preventing our models from being predisposed towards driving straight. This is proven by Figure 3.12b below, which exhibits a sample of 8,037 augmented images i.e. a more balanced distribution of the steering angles after augmentation. It is worth noting that the augmentation probability during training is set to 60%. In other words, not all of the original angles are altered, but a higher percentage would lead to a better spread. Hence, this is left as a future work.

![B048940A-8998-4E65-8233-E59C87824201](https://user-images.githubusercontent.com/42203067/175524078-fa4be09d-884d-4254-9c30-5cfb55843eb1.jpeg)

Hope this clarifies your concerns!
